import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Sidebar from '../components/Sidebar'
import { useEffect, useState } from 'react'

export default function Home() {

  const [ABI, setABI] = useState("");
  const [address, setAddress] = useState("");

  useEffect(() => { //testing to see if it works
    console.log(ABI)
  }, [ABI])

  return (
    <div className={styles.container}>
      <Head>
        <title>Contract Testor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Sidebar
        changeAddress = {setAddress} //calls setAddress(addy)
        changeABI = {setABI} //calls setABI(ABI)
      />

    </div>
  )
}
